
function mywaitbar2(N,w,h)
p=  axes('XLim',[0,N],...
        'YLim',[0,1],...  
        'Box','on',...
    'Units','pixel',...
    'Box','on',...
    'Position',[w,h,300,12],...
    'XTickMode','manual',...
    'YTickMode','manual',...
    'XTick',[],...
    'YTick',[],...
    'XTickLabelMode','manual',...
    'XTicklabel',[],...
    'YTickLabel',[],...
    'YTickLabelMode','manual',...
    'Visible','on',...
        'YTickLabel',[]);
    axes(p);
    for x=0:1:N
        xpatch=[0 x x 0];
        ypatch=[0 0 1 1];
        xline=[N 0 0 N N];
        yline=[0 0 1 1 0];
        p=patch(xpatch,ypatch,'r','EdgeColor','r');
        l=line(xline,yline);
        drawnow;
    end
    close all